/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MPIController */

#ifndef _Included_MPIController
#define _Included_MPIController
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     MPIController
 * Method:    loadGlobalLibraries
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_MPIController_loadGlobalLibraries
  (JNIEnv *, jclass);

/*
 * Class:     MPIController
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MPIController_init
  (JNIEnv *, jobject);

/*
 * Class:     MPIController
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MPIController_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     MPIController
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MPIController_finish
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
