/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFoo */

#ifndef _Included_JNIWrapper
#define _Included_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     JNIWrapper
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_hp_hpl_jni_JNIWrapper_run
  (JNIEnv *, jobject );

#ifdef __cplusplus
}
#endif
#endif
